import { accessSync, chmodSync, constants, existsSync, statSync, writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { join, resolve } from "node:path";
import { openDb } from "./db.js";
import { getProviderAdapters, resolveProviderExecutable } from "./providers/registry.js";
import type { ChainCliKind, ProviderId } from "./providers/types.js";
import { TelegramClient } from "./telegram.js";

const PROVIDER_TO_CHAIN_KIND: Record<ProviderId, ChainCliKind> = {
  codex: "codex",
  claude: "claude",
  agy: "antigravity",
  grok: "grok",
  cursor: "cursor",
};

const PROVIDER_COMMAND_ENV: Record<ProviderId, string> = {
  codex: "CODEX_COMMAND",
  claude: "CLAUDE_COMMAND",
  agy: "ANTIGRAVITY_COMMAND",
  grok: "GROK_COMMAND",
  cursor: "CURSOR_COMMAND",
};

const DEFAULT_CHAIN_ORDER: readonly ChainCliKind[] = [
  "codex",
  "claude",
  "grok",
  "antigravity",
  "cursor",
];

export interface DetectedInteractiveProvider {
  id: ProviderId;
  displayName: string;
  chainKind: ChainCliKind;
  commandEnv: string;
  commandPath: string;
}

export interface TelegramBotIdentity {
  id?: number;
  username?: string;
  firstName?: string;
}

export type CommandPathResolver = (command: string) => string | null;

export function assertSupportedNodeVersion(version = process.versions.node): void {
  const major = Number(version.split(".")[0]);
  if (!Number.isInteger(major) || major < 24) {
    throw new Error(`Agent Bridge source setup requires Node.js 24+ (current: ${version}).`);
  }
}

export function resolveCommandPath(command: string): string | null {
  if (command.includes("/")) {
    try {
      accessSync(command, constants.X_OK);
      return resolve(command);
    } catch {
      return null;
    }
  }

  try {
    const found = execFileSync("which", [command], { encoding: "utf8" }).trim();
    return found || null;
  } catch {
    return null;
  }
}

export function detectInteractiveProviders(options: {
  env?: Record<string, string | undefined>;
  resolvePath?: CommandPathResolver;
} = {}): DetectedInteractiveProvider[] {
  const env = options.env ?? process.env;
  const resolvePath = options.resolvePath ?? resolveCommandPath;
  const detected = getProviderAdapters()
    .filter((adapter) => adapter.capabilities.interactive)
    .flatMap((adapter) => {
      const configuredCommand = resolveProviderExecutable(adapter.id, env);
      const commandPath = resolvePath(configuredCommand);
      if (!commandPath) return [];
      return [{
        id: adapter.id,
        displayName: adapter.displayName,
        chainKind: PROVIDER_TO_CHAIN_KIND[adapter.id],
        commandEnv: PROVIDER_COMMAND_ENV[adapter.id],
        commandPath,
      }];
    });

  const order = new Map(DEFAULT_CHAIN_ORDER.map((kind, index) => [kind, index]));
  return detected.sort((a, b) => (order.get(a.chainKind) ?? 99) - (order.get(b.chainKind) ?? 99));
}

export function normalizeTelegramAllowedUserIds(raw: string): string {
  const ids = raw.split(",").map((value) => value.trim()).filter(Boolean);
  if (ids.length === 0) {
    throw new Error("At least one Telegram user ID is required.");
  }
  const invalid = ids.find((value) => !/^\d+$/.test(value));
  if (invalid) {
    throw new Error(`Invalid Telegram user ID: ${invalid}`);
  }
  return [...new Set(ids)].join(",");
}

function envValue(value: string): string {
  return JSON.stringify(value);
}

export function resolveSourceInteractiveDbPath(projectDir: string): string {
  return join(resolve(projectDir), ".data", "bridge.sqlite");
}

export function renderInteractiveSetupEnv(input: {
  telegramBotToken: string;
  telegramAllowedUserIds: string;
  projectDir: string;
  providers: readonly DetectedInteractiveProvider[];
}): string {
  const token = input.telegramBotToken.trim();
  if (!token) throw new Error("Telegram bot token is required.");
  const allowedUserIds = normalizeTelegramAllowedUserIds(input.telegramAllowedUserIds);
  const projectDir = resolve(input.projectDir);
  const dbPath = resolveSourceInteractiveDbPath(projectDir);
  if (input.providers.length === 0) throw new Error("At least one provider CLI is required.");

  const commandLines = input.providers.map((provider) =>
    `${provider.commandEnv}=${envValue(provider.commandPath)}`,
  );
  const chain = input.providers.map((provider) => provider.chainKind).join(",");

  return [
    "# Generated by `npm run setup` for the source interactive runtime.",
    "# Re-run with `npm run setup -- --force` to replace this file.",
    `TELEGRAM_BOT_TOKEN_INTERACTIVE=${envValue(token)}`,
    `TELEGRAM_ALLOWED_USER_IDS=${envValue(allowedUserIds)}`,
    `BRIDGE_PROJECT_DIR=${envValue(projectDir)}`,
    `DB_PATH=${envValue(dbPath)}`,
    "",
    ...commandLines,
    "",
    `INTERACTIVE_DEFAULT_CLI=${input.providers[0].chainKind}`,
    `INTERACTIVE_CLI_CHAIN=${chain}`,
    "BRIDGE_BUSY_MESSAGE_MODE=interrupt",
    "",
  ].join("\n");
}

export function validateProjectDirectory(rawPath: string): string {
  const projectDir = resolve(rawPath.trim());
  if (!rawPath.trim()) throw new Error("Project directory is required.");
  if (!existsSync(projectDir) || !statSync(projectDir).isDirectory()) {
    throw new Error(`Project directory does not exist: ${projectDir}`);
  }
  return projectDir;
}

export async function validateTelegramBotToken(
  token: string,
  fetchImpl: typeof fetch = fetch,
): Promise<TelegramBotIdentity> {
  const client = new TelegramClient(token.trim(), fetchImpl, 10_000);
  const response = await client.call<{ id?: number; username?: string; first_name?: string }>("getMe");
  return {
    id: response.result?.id,
    username: response.result?.username,
    firstName: response.result?.first_name,
  };
}

export function bootstrapSourceInteractiveDb(dbPath: string): void {
  const db = openDb(resolve(dbPath), {
    serviceId: "telegram:interactive-source-setup",
    databaseRole: "interactive",
  });
  db.raw.close();
}

export function writeInteractiveSetupConfig(
  configPath: string,
  content: string,
  options: { force?: boolean } = {},
): void {
  if (existsSync(configPath) && !options.force) {
    throw new Error(`${configPath} already exists. Re-run with --force to replace it.`);
  }
  writeFileSync(configPath, content, { encoding: "utf8", mode: 0o600 });
  chmodSync(configPath, 0o600);
}
